# See CONTRIBUTING.md for instructions.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Commitizen runs in commit-msg stage
# but we don't want to run the other hooks on commit messages
default_stages: [commit]

exclude: ^third_party/.*$
repos:
  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 6.3.3.1
    hooks:
      - id: buildifier
      - id: buildifier-lint
  # # Enforce that commit messages allow for later changelog generation
  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v2.18.0
  #   hooks:
  #     # Requires that commitizen is already installed
  #     - id: commitizen
  #       stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.3.0
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - flake8-import-restrictions
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
