[project]
name = "rules_pycross"
version = "0.0"
authors = []
requires-python = ">=3.8"
dependencies = [
    "build==1.0.3",
    "dacite==1.6.0",
    "importlib-metadata==6.8.0",
    "packaging==23.2",
    "pip==23.3.1",
    "poetry-core==1.8.1",
    "repairwheel==0.2.6",
    "tomli==2.0.1",
    "typing-extensions==4.8.0",
    "wheel==0.41.3",
]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.pylint]
line-length = 120

[tool.flakeheaven]
max_line_length = 120

[tool.flakeheaven.plugins]
"flake8-*" = ["+*"]
flake8-import-restrictions = ["+I2043"]
pyflakes = ["+*", "-F541"]

[tool.flakeheaven.exceptions."**/*.md"]
pyflakes = ["-*"]
